version: '3.1'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'diplom'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
  diplom_backend:
    build: server/
    image: pechenyice/diplom_backend:test
    environment:
      ENV: 'DOCKERDEV'
      PORT: '3001'
      DBHOST: 'mysql'
      DBUSER: 'root'
      DBPASS: 'root'
      DBNAME: 'diplom'
      TOKENLIFETIME: '300'
    depends_on: 
      - mysql
  diplom:
    build:
      context: .
      args:
        BACKEND_PORT: '3001'
    image: pechenyice/diplom:test
    ports:
      - "80:80"