version: '3.1'
services:
  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.9
    restart: always
    ports:
      - "5672:5672"
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'diplom'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
  diplom-backend:
    build: server/
    image: pechenyice/diplom-backend:test
    restart: always
    environment:
      ENV: 'DOCKERDEV'
      PORT: '3001'
      DBHOST: 'mysql'
      DBUSER: 'root'
      DBPASS: 'root'
      DBNAME: 'diplom'
      TOKENLIFETIME: '300'
      RESPONSEDELAY: '1000'
      RABBITURL: 'amqp://rabbitmq:5672'
      RPCQUEUE: 'rpc_queue'
      REDISHOST: 'redis'
      REDISPORT: '6379'
    depends_on: 
      - rabbitmq
      - mysql
  diplom-backend-services-dataManager:
    build: services/dataManager/
    image: pechenyice/diplom-service-data-manager:test
    restart: always
    environment:
      ENV: 'DOCKERDEV'
      DBHOST: 'mysql'
      DBUSER: 'root'
      DBPASS: 'root'
      DBNAME: 'diplom'
      TOKENLIFETIME: '300'
      RABBITURL: 'amqp://rabbitmq:5672'
      RPCQUEUE: 'rpc_queue'
      REDISHOST: 'redis'
      REDISPORT: '6379'
    depends_on: 
      - mysql
      - redis
      - rabbitmq
  diplom:
    build:
      context: .
      args:
        BACKEND_URL: 'diplom-backend:3001'
    links:
      - "diplom-backend:diplom-backend"
    image: pechenyice/diplom:test
    restart: always
    ports:
      - "80:80"