---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-wrong-pattern-local-isolated-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-local-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: diplom-local-test
    spec:
      containers:
      - image: redis:6.2
        name: redis
        ports:
        - containerPort: 6379
      - image: rabbitmq:3.9
        name: rabbitmq
        ports:
        - containerPort: 5672
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: 'diplom'
        - name: MYSQL_PASSWORD
          value: 'root'
        - name: MYSQL_ROOT_PASSWORD
          value: 'root'
        ports:
        - containerPort: 3306
      - image: pechenyice/diplom-service-data-manager:test
        name: diplom-service-data-manager
        command: ["node", "amqpServer.js"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: diplom-configmap
      - image: pechenyice/diplom-backend:test
        name: diplom-backend
        command: ["npm", "start"]
        imagePullPolicy: Always
        env:
        - name: PORT
          value: '3000'
        envFrom:
        - configMapRef:
            name: diplom-configmap
        ports:
        - containerPort: 3000
      - image: pechenyice/diplom:test
        name: diplom-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config
        configMap:
          name: nginx-config-map
...
